name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Read json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content test.json | ConvertFrom-Json
          echo "::set-output name=prop::$(echo $json.prop)"

      - run: echo ${{ steps.read-json.outputs}}
    