name: Test linux job
on:
  push

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send resource info to platform
        run: |
          python test.py ${{ github.repository }} main ${{ secrets.SOME }}
